title = "settings"

[database]
host = "localhost"
port = 3306
name = "stavkova"
user = "root"
password = "mostka"
charset = "utf8"
timezone = "Europe/Bratislava"

[system]
routine_count=100
similar_text_percent=70.0