CREATE TABLE `parse_site` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) DEFAULT NULL,
  `url` VARCHAR(200) DEFAULT NULL,
  `routines_count` INT(5) UNSIGNED DEFAULT '100',
  `tasks_per_time` INT(5) UNSIGNED DEFAULT '60',
  `wait_sec_per_tasks` INT(5) UNSIGNED DEFAULT '1',
  `enabled` TINYINT(1) UNSIGNED DEFAULT '0',
  `timezone` INT(2) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
